version: '3'

services:
  postgres:
    image: postgres:13
    ports:
      - "$DB_PORT:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
#  python:
#    image: python:3.9
#    command: python manage.py runserver